version: 1.4.2
mysql:
  host: ''
  port: ''
  user: ''
  pass: ''
  base: ''
language: en
metrics: 'true'
autoupdate: 'false'
uuid: 'false'
default_journal_slot: '-1'
max_npc_distance: '5'
global_locations: ''
