version: 1.5
mysql:
  host: ''
  port: ''
  user: ''
  pass: ''
  base: ''
language: en
metrics: 'true'
autoupdate: 'false'
uuid: 'false'
default_journal_slot: '-1'
max_npc_distance: '5'
tellraw: 'false'
sounds:
  start: 'VILLAGER_HAGGLE'
  end: 'VILLAGER_YES'
  journal: 'BAT_TAKEOFF'
  update: 'false'
  full: 'false'
global_locations: ''
