name: BetonQuest
main: pl.betoncraft.betonquest.BetonQuest
description: Advanced quest plugin
authors: [Co0sh, Dzejkop, BYK]
website: http://dev.bukkit.org/bukkit-plugins/betonquest/
softdepend: [Skript, Citizens, MythicMobs, Denizen, Vault, Multiverse-Core]
version: 1.7-dev
commands:
  q:
    description: General quest command
    usage: /<command>
    permission: betonquest.admin
    aliases: [bq, bquest, bquests, betonquest, betonquests, quest, quests]
  j:
    description: Adds journal to your inventory
    usage: /<command>
    permission: betonquest.journal
    aliases: [bj, journal, bjournal, betonjournal, b, bb, backpack, bbackpack, betonbackpack]
  questlang:
    description: Changes the language
    usage: /<command> lang
    permission: betonquest.language
  betonquestanswer:
    description: Handles tellraw answers
permissions:
  betonquest.admin:
    default: op
  betonquest.journal:
    default: true
  betonquest.conversation:
    default: true
  betonquest.language:
    default: true
  