name: BetonQuest
main: pl.betoncraft.betonquest.BetonQuest
description: Advanced quest plugin
authors: [Co0sh, Dzejkop, BYK]
website: http://dev.bukkit.org/bukkit-plugins/betonquest/
softdepend: [Citizens]
version: 1.3
commands:
  q:
    description: General quest command
    usage: /<command>
    permission: betonquest.admin
  j:
    description: Adds journal to your inventory
    usage: /<command>
    permission: betonquest.journal
permissions:
  betonquest.admin:
    default: op
  betonquest.createnpc:
    default: op
  betonquest.journal:
    default: true
  