name: BetonQuest
main: pl.betoncraft.betonquest.BetonQuest
version: 0.1
commands:
  q:
    description: General quest command
    usage: /<command>
permissions:
  betonquest.reload:
    default: op
  