name: BetonQuest
main: pl.betoncraft.betonquest.BetonQuest
authors: [Co0sh, Dzejkop, BYK]
website: http://betoncraft.pl/
depend: [Citizens]
version: 1.0
commands:
  q:
    description: General quest command
    usage: /<command>
permissions:
  betonquest.reload:
    default: op
  betonquest.objectives:
    default: op
  betonquest.tags:
    default: op
  betonquest.conditions:
    default: op
  